/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import {
  createFileRoute,
  createRootRoute,
  lazyRouteComponent,
} from '@tanstack/svelte-router'

import {
  Route as IndexRouteImport,
  default as IndexRouteComponent,
} from './routes/index.svelte'
import {
  Route as AboutRouteImport,
  default as AboutRouteComponent,
} from './routes/about.svelte'
import {
  Route as LListIdRouteImport,
  default as LListIdRouteComponent,
} from './routes/l.$listId.svelte'
import {
  Route as PSlugRouteImport,
  default as PSlugRouteComponent,
} from './routes/p.$slug.svelte'

const rootRouteImport = createRootRoute()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: IndexRouteComponent,
})
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: AboutRouteComponent,
})
const LListIdRoute = LListIdRouteImport.update({
  id: '/l/$listId',
  path: '/l/$listId',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: LListIdRouteComponent,
})
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: PSlugRouteComponent,
})

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/l/$listId': typeof LListIdRoute
  '/p/$slug': typeof PSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/l/$listId': typeof LListIdRoute
  '/p/$slug': typeof PSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/l/$listId': typeof LListIdRoute
  '/p/$slug': typeof PSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/l/$listId' | '/p/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/l/$listId' | '/p/$slug'
  id: '__root__' | '/' | '/about' | '/l/$listId' | '/p/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LListIdRoute: typeof LListIdRoute
  PSlugRoute: typeof PSlugRoute
}

declare module '@tanstack/svelte-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/l/$listId': {
      id: '/l/$listId'
      path: '/l/$listId'
      fullPath: '/l/$listId'
      preLoaderRoute: typeof LListIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LListIdRoute: LListIdRoute,
  PSlugRoute: PSlugRoute,
}
export const routeTree = rootRouteImport
  .update({
    component: lazyRouteComponent(
      () => import('./routes/__root.svelte'),
      'default',
    ),
  })
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { createStart } from '@tanstack/svelte-start'
declare module '@tanstack/svelte-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
